In [6]:
import cv2
import numpy as np
import os
import glob
 
# Defining the dimensions of checkerboard
CHECKERBOARD = (6,8)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 
 
 
# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
 
# Extracting path of individual image stored in a given directory
#images = glob.glob('./test/*.png')
images = glob.glob('./logitech_frames/*.png')
#images = glob.glob('./s23_frames/*.jpg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
     
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
    cv2.imshow('img',img)
    cv2.waitKey(0)
 
cv2.destroyAllWindows()
 
h,w = img.shape[:2]
 
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)

Camera matrix : 

[[626.50494838   0.         311.09117891]
 [  0.         627.50681747 233.49381065]
 [  0.           0.           1.        ]]
dist : 

[[ 1.12753281e-01  9.35202425e-02 -1.05467911e-03 -2.88927114e-03
  -1.29921330e+00]]
rvecs : 

(array([[0.80141993],
       [0.06460735],
       [1.40571793]]), array([[ 0.35472949],
       [-0.09848582],
       [ 1.36206562]]), array([[ 0.19138533],
       [-0.13502506],
       [ 1.50022592]]), array([[0.1523458 ],
       [0.07434871],
       [1.53104797]]), array([[ 0.06860058],
       [ 0.13869367],
       [-1.45761448]]), array([[ 0.26563695],
       [-0.20387652],
       [ 1.52020006]]), array([[-0.37293624],
       [-0.22828346],
       [-1.33245738]]), array([[0.16053758],
       [0.13956893],
       [1.56915608]]))
tvecs : 

(array([[ 6.7975561 ],
       [-5.46895902],
       [19.85703354]]), array([[ 4.89541584],
       [-4.15024508],
       [19.16423458]]), array([[ 6.44083338],
       [-3.69826773],
       [19.25579012]]),